version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - docker version
      - java --version
  build:
    commands:
      - ./gradlew clean test
reports:
  unit-tests:
    files:
      - "build/test-results/test/*.xml"
    file-format: "JUNITXML"