version: 0.2

phases:
  install:
    commands:
      - echo "Updating Lambda Function = $FUNCTION_NAME"
      - echo "New Image = $IMAGE_URI"
  build:
    commands:
      - export CURRENT_LAMBDA_VERSION=`aws lambda get-alias --function-name $FUNCTION_NAME --name $FUNCTION_ALIAS --query 'FunctionVersion' --output text`
      - export NEW_LAMBDA_VERSION=`aws lambda update-function-code --function-name $FUNCTION_NAME --image-uri $IMAGE_URI --publish --query 'Version' --output text`
      - echo $APPSPEC_TEMPLATE
      - echo $APPSPEC_TEMPLATE
      - touch "appspec.json"
      - echo $APPSPEC_TEMPLATE > appspec.json
      - jq -c '.Resources[0].$FUNCTION_NAME.Properties.CurrentVersion="$CURRENT_LAMBDA_VERSION"' appspec.json > appspec.json
      - jq -c '.Resources[0].$FUNCTION_NAME.Properties.TargetVersion="$NEW_LAMBDA_VERSION"' appspec.json > appspec.json

artifacts:
  files:
    - appspec.json